package com.muqui.model;
// Generated 7/10/2019 05:13:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="usuario"
)
public class User  implements java.io.Serializable {


     private int id;
     private String lastName;
     private String firstName;
     private Integer age;

    public User() {
    }

	
    public User(int id, String lastName) {
        this.id = id;
        this.lastName = lastName;
    }
    public User(int id, String lastName, String firstName, Integer age) {
       this.id = id;
       this.lastName = lastName;
       this.firstName = firstName;
       this.age = age;
    }
    public User( String lastName, String firstName, Integer age) {
      
       this.lastName = lastName;
       this.firstName = firstName;
       this.age = age;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="LastName", nullable=false)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="FirstName")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="Age")
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }




}


